namespace DemoFluentUI.Components.Pages;

using Microsoft.AspNetCore.Components;

public record Country(string Code, string Name)
{
    public string Flag => $"https://fluentui-blazor.net/_content/FluentUI.Demo.Shared/flags/{Code}.svg";

    public MarkupString HtmlFlagAndName => (MarkupString)
        @$"<div style=""display: flex; gap: 10px;"">
               <img src=""{Flag}"" width=""24"" />
               <div>{Name}</div>
           </div>";

    public static IEnumerable<Country> All
    {
        get
        {
            // List generated using https://chat.openai.com/
            return new Country[]
            {
                new Country("af", "Afghanistan"),
                new Country("al", "Albania"),
                new Country("dz", "Algeria"),
                new Country("as", "American Samoa"),
                new Country("ad", "Andorra"),
                new Country("ao", "Angola"),
                new Country("ai", "Anguilla"),
                new Country("aq", "Antarctica"),
                new Country("ag", "Antigua and Barbuda"),
                new Country("ar", "Argentina"),
                new Country("am", "Armenia"),
                new Country("aw", "Aruba"),
                new Country("au", "Australia"),
                new Country("at", "Austria"),
                new Country("az", "Azerbaijan"),
                new Country("bs", "Bahamas"),
                new Country("bh", "Bahrain"),
                new Country("bd", "Bangladesh"),
                new Country("bb", "Barbados"),
                new Country("by", "Belarus"),
                new Country("be", "Belgium"),
                new Country("bz", "Belize"),
                new Country("bj", "Benin"),
                new Country("bm", "Bermuda"),
                new Country("bt", "Bhutan"),
                new Country("bo", "Bolivia"),
                new Country("bq", "Bonaire, Sint Eustatius, and Saba"),
                new Country("ba", "Bosnia and Herzegovina"),
                new Country("bw", "Botswana"),
                new Country("bv", "Bouvet Island"),
                new Country("br", "Brazil"),
                new Country("io", "British Indian Ocean Territory"),
                new Country("vg", "British Virgin Islands"),
                new Country("bn", "Brunei"),
                new Country("bg", "Bulgaria"),
                new Country("bf", "Burkina Faso"),
                new Country("bi", "Burundi"),
                new Country("cv", "Cabo Verde"),
                new Country("kh", "Cambodia"),
                new Country("cm", "Cameroon"),
                new Country("ca", "Canada"),
                new Country("ky", "Cayman Islands"),
                new Country("cf", "Central African Republic"),
                new Country("td", "Chad"),
                new Country("cl", "Chile"),
                new Country("cn", "China"),
                new Country("cx", "Christmas Island"),
                new Country("cc", "Cocos (Keeling) Islands"),
                new Country("co", "Colombia"),
                new Country("km", "Comoros"),
                new Country("cd", "Congo (Congo-Kinshasa)"),
                new Country("ck", "Cook Islands"),
                new Country("cr", "Costa Rica"),
                new Country("hr", "Croatia"),
                new Country("cu", "Cuba"),
                new Country("cw", "Curaçao"),
                new Country("cy", "Cyprus"),
                new Country("cz", "Czech Republic"),
                new Country("ci", "Côte d'Ivoire"),
                new Country("kp", "Democratic People's Republic of Korea (North Korea)"),
                new Country("dk", "Denmark"),
                new Country("dj", "Djibouti"),
                new Country("dm", "Dominica"),
                new Country("do", "Dominican Republic"),
                new Country("ec", "Ecuador"),
                new Country("eg", "Egypt"),
                new Country("sv", "El Salvador"),
                new Country("gq", "Equatorial Guinea"),
                new Country("er", "Eritrea"),
                new Country("ee", "Estonia"),
                new Country("sz", "Eswatini"),
                new Country("et", "Ethiopia"),
                new Country("fk", "Falkland Islands (Malvinas)"),
                new Country("fo", "Faroe Islands"),
                new Country("fj", "Fiji"),
                new Country("fi", "Finland"),
                new Country("fr", "France"),
                new Country("gf", "French Guiana"),
                new Country("pf", "French Polynesia"),
                new Country("tf", "French Southern Territories"),
                new Country("ga", "Gabon"),
                new Country("gm", "Gambia"),
                new Country("ge", "Georgia"),
                new Country("de", "Germany"),
                new Country("gh", "Ghana"),
                new Country("gi", "Gibraltar"),
                new Country("gr", "Greece"),
                new Country("gl", "Greenland"),
                new Country("gd", "Grenada"),
                new Country("gp", "Guadeloupe"),
                new Country("gu", "Guam"),
                new Country("gt", "Guatemala"),
                new Country("gg", "Guernsey"),
                new Country("gn", "Guinea"),
                new Country("gw", "Guinea-Bissau"),
                new Country("gy", "Guyana"),
                new Country("ht", "Haiti"),
                new Country("hm", "Heard Island and McDonald Islands"),
                new Country("va", "Holy See"),
                new Country("hn", "Honduras"),
                new Country("hk", "Hong Kong"),
                new Country("hu", "Hungary"),
                new Country("is", "Iceland"),
                new Country("in", "India"),
                new Country("id", "Indonesia"),
                new Country("ir", "Iran"),
                new Country("iq", "Iraq"),
                new Country("ie", "Ireland"),
                new Country("im", "Isle of Man"),
                new Country("il", "Israel"),
                new Country("it", "Italy"),
                new Country("jm", "Jamaica"),
                new Country("jp", "Japan"),
                new Country("je", "Jersey"),
                new Country("jo", "Jordan"),
                new Country("kz", "Kazakhstan"),
                new Country("ke", "Kenya"),
                new Country("ki", "Kiribati"),
                new Country("kw", "Kuwait"),
                new Country("kg", "Kyrgyzstan"),
                new Country("la", "Lao People's Democratic Republic"),
                new Country("lv", "Latvia"),
                new Country("lb", "Lebanon"),
                new Country("ls", "Lesotho"),
                new Country("lr", "Liberia"),
                new Country("ly", "Libya"),
                new Country("li", "Liechtenstein"),
                new Country("lt", "Lithuania"),
                new Country("lu", "Luxembourg"),
                new Country("mo", "Macao"),
                new Country("mg", "Madagascar"),
                new Country("mw", "Malawi"),
                new Country("my", "Malaysia"),
                new Country("mv", "Maldives"),
                new Country("ml", "Mali"),
                new Country("mt", "Malta"),
                new Country("mh", "Marshall Islands"),
                new Country("mq", "Martinique"),
                new Country("mr", "Mauritania"),
                new Country("mu", "Mauritius"),
                new Country("yt", "Mayotte"),
                new Country("mx", "Mexico"),
                new Country("fm", "Micronesia"),
                new Country("md", "Moldova"),
                new Country("mc", "Monaco"),
                new Country("mn", "Mongolia"),
                new Country("me", "Montenegro"),
                new Country("ms", "Montserrat"),
                new Country("ma", "Morocco"),
                new Country("mz", "Mozambique"),
                new Country("mm", "Myanmar"),
                new Country("na", "Namibia"),
                new Country("nr", "Nauru"),
                new Country("np", "Nepal"),
                new Country("nl", "Netherlands"),
                new Country("nc", "New Caledonia"),
                new Country("nz", "New Zealand"),
                new Country("ni", "Nicaragua"),
                new Country("ne", "Niger"),
                new Country("ng", "Nigeria"),
                new Country("nu", "Niue"),
                new Country("nf", "Norfolk Island"),
                new Country("mp", "Northern Mariana Islands"),
                new Country("no", "Norway"),
                new Country("om", "Oman"),
                new Country("pk", "Pakistan"),
                new Country("ps", "Palestine"),
                new Country("pa", "Panama"),
                new Country("pg", "Papua New Guinea"),
                new Country("py", "Paraguay"),
                new Country("pe", "Peru"),
                new Country("ph", "Philippines"),
                new Country("pn", "Pitcairn"),
                new Country("pl", "Poland"),
                new Country("pt", "Portugal"),
                new Country("pr", "Puerto Rico"),
                new Country("qa", "Qatar"),
                new Country("kr", "Republic of Korea (South Korea)"),
                new Country("md", "Republic of Moldova"),
                new Country("ro", "Romania"),
                new Country("ru", "Russian Federation"),
                new Country("rw", "Rwanda"),
                new Country("re", "Réunion"),
                new Country("bl", "Saint Barthélemy"),
                new Country("sh", "Saint Helena"),
                new Country("kn", "Saint Kitts and Nevis"),
                new Country("lc", "Saint Lucia"),
                new Country("mf", "Saint Martin"),
                new Country("pm", "Saint Pierre and Miquelon"),
                new Country("vc", "Saint Vincent and the Grenadines"),
                new Country("ws", "Samoa"),
                new Country("sm", "San Marino"),
                new Country("st", "Sao Tome and Principe"),
                new Country("sa", "Saudi Arabia"),
                new Country("sn", "Senegal"),
                new Country("rs", "Serbia"),
                new Country("sc", "Seychelles"),
                new Country("sl", "Sierra Leone"),
                new Country("sg", "Singapore"),
                new Country("sx", "Sint Maarten"),
                new Country("sk", "Slovakia"),
                new Country("si", "Slovenia"),
                new Country("sb", "Solomon Islands"),
                new Country("so", "Somalia"),
                new Country("za", "South Africa"),
                new Country("gs", "South Georgia and the South Sandwich Islands"),
                new Country("ss", "South Sudan"),
                new Country("es", "Spain"),
                new Country("lk", "Sri Lanka"),
                new Country("sd", "Sudan"),
                new Country("sr", "Suriname"),
                new Country("sj", "Svalbard and Jan Mayen"),
                new Country("se", "Sweden"),
                new Country("ch", "Switzerland"),
                new Country("sy", "Syria"),
                new Country("tw", "Taiwan"),
                new Country("tj", "Tajikistan"),
                new Country("th", "Thailand"),
                new Country("mk", "The Former Yugoslav Republic of Macedonia"),
                new Country("tl", "Timor-Leste"),
                new Country("tg", "Togo"),
                new Country("tk", "Tokelau"),
                new Country("to", "Tonga"),
                new Country("tt", "Trinidad and Tobago"),
                new Country("tn", "Tunisia"),
                new Country("tr", "Turkey"),
                new Country("tm", "Turkmenistan"),
                new Country("tc", "Turks and Caicos Islands"),
                new Country("tv", "Tuvalu"),
                new Country("ug", "Uganda"),
                new Country("ua", "Ukraine"),
                new Country("ae", "United Arab Emirates"),
                new Country("gb", "United Kingdom"),
                new Country("us", "United States of America"),
                new Country("vi", "United States Virgin Islands"),
                new Country("uy", "Uruguay"),
                new Country("uz", "Uzbekistan"),
                new Country("vu", "Vanuatu"),
                new Country("ve", "Venezuela"),
                new Country("vn", "Vietnam"),
                new Country("wf", "Wallis and Futuna"),
                new Country("eh", "Western Sahara"),
                new Country("ye", "Yemen"),
                new Country("zm", "Zambia"),
                new Country("zw", "Zimbabwe"),
            };
        }
    }
}